title: "Ziwen Kan"
description: "Ph.D. student | Multimodal Learning"
theme: minima

header_pages:
  - index.md
  - about.md
  - publications.md
  - projects.md
  - education.md
  - cv.md
  - miscellaneous.md

markdown: kramdown
plugins:
  - jekyll-feed

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/ziwenkan" }
